# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='picture',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
